import type { Metadata } from "next";
import Nav from "../components/Nav";
import { UserLogin } from '../interfaces/UserLogin';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const userLogin: UserLogin = {
    firstName: "John",
    lastName: "Doe",
    status: "Active",
    urlAvatar: "/img/favicon.jpg",
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav userLogin={userLogin} />
        {children}
      </body>
    </html>
  );
}
